spring.application.name=backend

# 1. 프로필 포함 설정
spring.profiles.include=secrets

# 2. PostgreSQL 드라이버 및 방언 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. AWS 공통 설정
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.stack.auto=false